name: Create Plugin Zip
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        type: string
        default: ''
    outputs:
      artifact-name:
        description: 'The name of the uploaded artifact'
        value: ${{ jobs.generate-archive.outputs.artifact-name }}

jobs:
  generate-archive:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: notificationx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          path: notificationx

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, wp-cli

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: notificationx

      - name: Build assets
        run: npm run release
        working-directory: notificationx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notificationx
          path: notificationx
          retention-days: 1